### ISSUE TITLE
Extended your sample with examples for dictation 

### ISSUE THREAD

**Issue by shacharoz** [LightBuzz/Speech-Recognition-Unity#2]
Would you like to share that code here? Or will you prefer I duplicate the repo?

**Comment by Vangos** [comment]
Thanks for your comment! You can create a pull request and I'll merge from my end.

**Comment by shacharoz** [comment]
do you prefer i will keep the same folder structure, and only add more
files, or can i change it?
im going to add a folder per use case of WordRecognition,
GrammarRecognition, DictationRecognition.

what do you think?


Shachar Oz
Design & Business for
Emergent Tech Products
flux-experiences.com/design
Portfolio <https://behance.net/shacharoz>  | +39-351-519-0003

**Comment by Vangos** [comment]
Whatever works for you.

**Comment by shacharoz** [comment]
ok.
created a fork and a pull request. but i compiled with 2019. can you try to
compile the same code with 5.5? or must i do that?

Shachar Oz
Design & Business for
Emergent Tech Products
flux-experiences.com/design
Portfolio <https://behance.net/shacharoz>  | +39-351-519-0003

**Comment by Vangos** [comment]
I have merged your pull request. Thank you very much. Looks great :) 

Will test on additional Unity versions later, too.

**Comment by shacharoz** [comment]
Cool. Now we need to write another article :)
Is it ok if I write it? Will you guys support it? Is it ok if I say I
contributed to this?

**Comment by Vangos** [comment]
That would be awesome! Feel free to write the article and upload it on Google Drive or Dropbox. Then, share the link using [our contact form](https://lightbuzz.com/contact).

Feel free to add a short bio, too.

We would be happy to publish the article with your name and bio.
